export interface Database {
  public: {
    Tables: {
      waitlist_signups: {
        Row: {
          id: string;
          name: string | null;
          email: string;
          phone_number: string | null;
          consent: boolean;
          marketing_consent: boolean;
          referral_code: string | null;
          source: string | null;
          status: string | null;
          priority: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_term: string | null;
          utm_content: string | null;
          user_agent: string | null;
          screen_resolution: string | null;
          language: string | null;
          timezone: string | null;
          browser: string | null;
          browser_version: string | null;
          os: string | null;
          os_version: string | null;
          device_name: string | null;
          device_model: string | null;
          device_manufacturer: string | null;
          device_type: string | null;
          is_mobile: boolean;
          is_tablet: boolean;
          is_desktop: boolean;
          ip_address: string | null;
          country: string | null;
          city: string | null;
          state: string | null;
          latitude: number | null;
          longitude: number | null;
          scroll_depth: number | null;
          time_on_page: number | null;
          referrer: string | null;
          landing_page: string | null;
          session_id: string | null;
          page_load_time: number | null;
          network_speed: string | null;
          connection_type: string | null;
          cpu_cores: number | null;
          memory_gb: number | null;
          color_depth: number | null;
          pixel_ratio: number | null;
          viewport_width: number | null;
          viewport_height: number | null;
          touch_support: boolean;
          webgl_support: boolean;
          cookie_enabled: boolean;
          do_not_track: boolean;
          ad_blocker_detected: boolean;
          javascript_enabled: boolean;
          flash_enabled: boolean;
          java_enabled: boolean;
          silverlight_enabled: boolean;
          pdf_viewer: string | null;
          quicktime_enabled: boolean;
          realplayer_enabled: boolean;
          windowsmedia_enabled: boolean;
          vlc_enabled: boolean;
          shockwave_enabled: boolean;
          activex_enabled: boolean;
          vbs_enabled: boolean;
          vb_enabled: boolean;
          perl_enabled: boolean;
          python_enabled: boolean;
          ruby_enabled: boolean;
          php_enabled: boolean;
          asp_enabled: boolean;
          jsp_enabled: boolean;
          coldfusion_enabled: boolean;
          cgi_enabled: boolean;
          isp: string | null;
          organization: string | null;
          as_number: string | null;
          proxy_detected: boolean;
          vpn_detected: boolean;
          tor_detected: boolean;
          bot_detected: boolean;
          fraud_score: number;
          risk_level: string;
          notes: string | null;
          engagement_score: number | null;
          conversion_probability: number | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          name?: string | null;
          email: string;
          phone_number?: string | null;
          consent?: boolean;
          marketing_consent?: boolean;
          referral_code?: string | null;
          source?: string | null;
          status?: string | null;
          priority?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          user_agent?: string | null;
          screen_resolution?: string | null;
          language?: string | null;
          timezone?: string | null;
          browser?: string | null;
          browser_version?: string | null;
          os?: string | null;
          os_version?: string | null;
          device_name?: string | null;
          device_model?: string | null;
          device_manufacturer?: string | null;
          device_type?: string | null;
          is_mobile?: boolean;
          is_tablet?: boolean;
          is_desktop?: boolean;
          ip_address?: string | null;
          country?: string | null;
          city?: string | null;
          state?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          scroll_depth?: number | null;
          time_on_page?: number | null;
          referrer?: string | null;
          landing_page?: string | null;
          session_id?: string | null;
          page_load_time?: number | null;
          network_speed?: string | null;
          connection_type?: string | null;
          cpu_cores?: number | null;
          memory_gb?: number | null;
          color_depth?: number | null;
          pixel_ratio?: number | null;
          viewport_width?: number | null;
          viewport_height?: number | null;
          touch_support?: boolean;
          webgl_support?: boolean;
          cookie_enabled?: boolean;
          do_not_track?: boolean;
          ad_blocker_detected?: boolean;
          javascript_enabled?: boolean;
          flash_enabled?: boolean;
          java_enabled?: boolean;
          silverlight_enabled?: boolean;
          pdf_viewer?: string | null;
          quicktime_enabled?: boolean;
          realplayer_enabled?: boolean;
          windowsmedia_enabled?: boolean;
          vlc_enabled?: boolean;
          shockwave_enabled?: boolean;
          activex_enabled?: boolean;
          vbs_enabled?: boolean;
          vb_enabled?: boolean;
          perl_enabled?: boolean;
          python_enabled?: boolean;
          ruby_enabled?: boolean;
          php_enabled?: boolean;
          asp_enabled?: boolean;
          jsp_enabled?: boolean;
          coldfusion_enabled?: boolean;
          cgi_enabled?: boolean;
          isp?: string | null;
          organization?: string | null;
          as_number?: string | null;
          proxy_detected?: boolean;
          vpn_detected?: boolean;
          tor_detected?: boolean;
          bot_detected?: boolean;
          fraud_score?: number;
          risk_level?: string;
          notes?: string | null;
          engagement_score?: number | null;
          conversion_probability?: number | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string | null;
          email?: string;
          phone_number?: string | null;
          consent?: boolean;
          marketing_consent?: boolean;
          referral_code?: string | null;
          source?: string | null;
          status?: string | null;
          priority?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          user_agent?: string | null;
          screen_resolution?: string | null;
          language?: string | null;
          timezone?: string | null;
          browser?: string | null;
          browser_version?: string | null;
          os?: string | null;
          os_version?: string | null;
          device_name?: string | null;
          device_model?: string | null;
          device_manufacturer?: string | null;
          device_type?: string | null;
          is_mobile?: boolean;
          is_tablet?: boolean;
          is_desktop?: boolean;
          ip_address?: string | null;
          country?: string | null;
          city?: string | null;
          state?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          scroll_depth?: number | null;
          time_on_page?: number | null;
          referrer?: string | null;
          landing_page?: string | null;
          session_id?: string | null;
          page_load_time?: number | null;
          network_speed?: string | null;
          connection_type?: string | null;
          cpu_cores?: number | null;
          memory_gb?: number | null;
          color_depth?: number | null;
          pixel_ratio?: number | null;
          viewport_width?: number | null;
          viewport_height?: number | null;
          touch_support?: boolean;
          webgl_support?: boolean;
          cookie_enabled?: boolean;
          do_not_track?: boolean;
          ad_blocker_detected?: boolean;
          javascript_enabled?: boolean;
          flash_enabled?: boolean;
          java_enabled?: boolean;
          silverlight_enabled?: boolean;
          pdf_viewer?: string | null;
          quicktime_enabled?: boolean;
          realplayer_enabled?: boolean;
          windowsmedia_enabled?: boolean;
          vlc_enabled?: boolean;
          shockwave_enabled?: boolean;
          activex_enabled?: boolean;
          vbs_enabled?: boolean;
          vb_enabled?: boolean;
          perl_enabled?: boolean;
          python_enabled?: boolean;
          ruby_enabled?: boolean;
          php_enabled?: boolean;
          asp_enabled?: boolean;
          jsp_enabled?: boolean;
          coldfusion_enabled?: boolean;
          cgi_enabled?: boolean;
          isp?: string | null;
          organization?: string | null;
          as_number?: string | null;
          proxy_detected?: boolean;
          vpn_detected?: boolean;
          tor_detected?: boolean;
          bot_detected?: boolean;
          fraud_score?: number;
          risk_level?: string;
          notes?: string | null;
          engagement_score?: number | null;
          conversion_probability?: number | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          subject: string;
          message: string;
          phone_number: string | null;
          consent: boolean;
          marketing_consent: boolean;
          referral_source: string | null;
          status: string;
          priority: string;
          category: string;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_term: string | null;
          utm_content: string | null;
          user_agent: string | null;
          screen_resolution: string | null;
          language: string | null;
          timezone: string | null;
          browser: string | null;
          browser_version: string | null;
          os: string | null;
          os_version: string | null;
          device_name: string | null;
          device_model: string | null;
          device_manufacturer: string | null;
          device_type: string | null;
          is_mobile: boolean;
          is_tablet: boolean;
          is_desktop: boolean;
          ip_address: string | null;
          country: string | null;
          city: string | null;
          state: string | null;
          latitude: number | null;
          longitude: number | null;
          scroll_depth: number | null;
          time_on_page: number | null;
          referrer: string | null;
          landing_page: string | null;
          session_id: string | null;
          page_load_time: number | null;
          network_speed: string | null;
          connection_type: string | null;
          cpu_cores: number | null;
          memory_gb: number | null;
          color_depth: number | null;
          pixel_ratio: number | null;
          viewport_width: number | null;
          viewport_height: number | null;
          touch_support: boolean;
          webgl_support: boolean;
          cookie_enabled: boolean;
          do_not_track: boolean;
          ad_blocker_detected: boolean;
          javascript_enabled: boolean;
          flash_enabled: boolean;
          java_enabled: boolean;
          silverlight_enabled: boolean;
          pdf_viewer: string | null;
          quicktime_enabled: boolean;
          realplayer_enabled: boolean;
          windowsmedia_enabled: boolean;
          vlc_enabled: boolean;
          shockwave_enabled: boolean;
          activex_enabled: boolean;
          vbs_enabled: boolean;
          vb_enabled: boolean;
          perl_enabled: boolean;
          python_enabled: boolean;
          ruby_enabled: boolean;
          php_enabled: boolean;
          asp_enabled: boolean;
          jsp_enabled: boolean;
          coldfusion_enabled: boolean;
          cgi_enabled: boolean;
          isp: string | null;
          organization: string | null;
          as_number: string | null;
          proxy_detected: boolean;
          vpn_detected: boolean;
          tor_detected: boolean;
          bot_detected: boolean;
          fraud_score: number;
          risk_level: string;
          notes: string | null;
          engagement_score: number | null;
          conversion_probability: number | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          subject: string;
          message: string;
          phone_number?: string | null;
          consent?: boolean;
          marketing_consent?: boolean;
          referral_source?: string | null;
          status?: string;
          priority?: string;
          category?: string;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          user_agent?: string | null;
          screen_resolution?: string | null;
          language?: string | null;
          timezone?: string | null;
          browser?: string | null;
          browser_version?: string | null;
          os?: string | null;
          os_version?: string | null;
          device_name?: string | null;
          device_model?: string | null;
          device_manufacturer?: string | null;
          device_type?: string | null;
          is_mobile?: boolean;
          is_tablet?: boolean;
          is_desktop?: boolean;
          ip_address?: string | null;
          country?: string | null;
          city?: string | null;
          state?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          scroll_depth?: number | null;
          time_on_page?: number | null;
          referrer?: string | null;
          landing_page?: string | null;
          session_id?: string | null;
          page_load_time?: number | null;
          network_speed?: string | null;
          connection_type?: string | null;
          cpu_cores?: number | null;
          memory_gb?: number | null;
          color_depth?: number | null;
          pixel_ratio?: number | null;
          viewport_width?: number | null;
          viewport_height?: number | null;
          touch_support?: boolean;
          webgl_support?: boolean;
          cookie_enabled?: boolean;
          do_not_track?: boolean;
          ad_blocker_detected?: boolean;
          javascript_enabled?: boolean;
          flash_enabled?: boolean;
          java_enabled?: boolean;
          silverlight_enabled?: boolean;
          pdf_viewer?: string | null;
          quicktime_enabled?: boolean;
          realplayer_enabled?: boolean;
          windowsmedia_enabled?: boolean;
          vlc_enabled?: boolean;
          shockwave_enabled?: boolean;
          activex_enabled?: boolean;
          vbs_enabled?: boolean;
          vb_enabled?: boolean;
          perl_enabled?: boolean;
          python_enabled?: boolean;
          ruby_enabled?: boolean;
          php_enabled?: boolean;
          asp_enabled?: boolean;
          jsp_enabled?: boolean;
          coldfusion_enabled?: boolean;
          cgi_enabled?: boolean;
          isp?: string | null;
          organization?: string | null;
          as_number?: string | null;
          proxy_detected?: boolean;
          vpn_detected?: boolean;
          tor_detected?: boolean;
          bot_detected?: boolean;
          fraud_score?: number;
          risk_level?: string;
          notes?: string | null;
          engagement_score?: number | null;
          conversion_probability?: number | null;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          subject?: string;
          message?: string;
          phone_number?: string | null;
          consent?: boolean;
          marketing_consent?: boolean;
          referral_source?: string | null;
          status?: string;
          priority?: string;
          category?: string;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_term?: string | null;
          utm_content?: string | null;
          user_agent?: string | null;
          screen_resolution?: string | null;
          language?: string | null;
          timezone?: string | null;
          browser?: string | null;
          browser_version?: string | null;
          os?: string | null;
          os_version?: string | null;
          device_name?: string | null;
          device_model?: string | null;
          device_manufacturer?: string | null;
          device_type?: string | null;
          is_mobile?: boolean;
          is_tablet?: boolean;
          is_desktop?: boolean;
          ip_address?: string | null;
          country?: string | null;
          city?: string | null;
          state?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          scroll_depth?: number | null;
          time_on_page?: number | null;
          referrer?: string | null;
          landing_page?: string | null;
          session_id?: string | null;
          page_load_time?: number | null;
          network_speed?: string | null;
          connection_type?: string | null;
          cpu_cores?: number | null;
          memory_gb?: number | null;
          color_depth?: number | null;
          pixel_ratio?: number | null;
          viewport_width?: number | null;
          viewport_height?: number | null;
          touch_support?: boolean;
          webgl_support?: boolean;
          cookie_enabled?: boolean;
          do_not_track?: boolean;
          ad_blocker_detected?: boolean;
          javascript_enabled?: boolean;
          flash_enabled?: boolean;
          java_enabled?: boolean;
          silverlight_enabled?: boolean;
          pdf_viewer?: string | null;
          quicktime_enabled?: boolean;
          realplayer_enabled?: boolean;
          windowsmedia_enabled?: boolean;
          vlc_enabled?: boolean;
          shockwave_enabled?: boolean;
          activex_enabled?: boolean;
          vbs_enabled?: boolean;
          vb_enabled?: boolean;
          perl_enabled?: boolean;
          python_enabled?: boolean;
          ruby_enabled?: boolean;
          php_enabled?: boolean;
          asp_enabled?: boolean;
          jsp_enabled?: boolean;
          coldfusion_enabled?: boolean;
          cgi_enabled?: boolean;
          isp?: string | null;
          organization?: string | null;
          as_number?: string | null;
          proxy_detected?: boolean;
          vpn_detected?: boolean;
          tor_detected?: boolean;
          bot_detected?: boolean;
          fraud_score?: number;
          risk_level?: string;
          notes?: string | null;
          engagement_score?: number | null;
          conversion_probability?: number | null;
          created_at?: string;
          updated_at?: string | null;
        };
      };
    };
    Views: {
      // No views defined
    };
    Functions: {
      // No functions defined
    };
    Enums: {
      // No enums defined
    };
  };
}
